---
- name: Deploy common packagae for Clustes Kubernetes
  hosts: all 
  become: true
  roles:
    - role: k8s-common

- name: Deploy do Clustes Kubernetes for master
  hosts: k8s-control-plane 
  become: true
  roles:
    - { role: k8s-control-plane }

- name: Deploy do Clustes Kubernetes for nodes
  hosts: k8s-worker-node-*
  become: true
  roles:
    - { role: k8s-worker-nodes }            