---
# tasks file for k8s-worker-nodes
# This playbook is for worker nodes in a Kubernetes cluster.
# It configures the node, installs necessary packages, and joins the node to the cluster.
# It assumes that the control plane has already been set up and the join command is available.
# The playbook is designed to be run on each worker node in the cluster.
# It uses the Ansible lineinfile module to ensure that the kubelet configuration is set correctly.
# It also uses the Ansible service module to restart the kubelet service after making changes.
# The playbook includes tasks to install necessary packages, configure the node IP, and join the node to the cluster.

- name: Configure node ip
  lineinfile:
    create: true
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted    

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777
  become: true
 
- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  become: true
  

